### ISSUE TITLE
Download links are broken on master

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#100]
I missed introducing ```use_branch``` to the ``_get_filename`` function, so downloads currently throw a server error.

**Comment by Bjwebb** [comment]
We've not seen this error through Sentry, so I'll chase up whether that's configured properly.

**Comment by Bjwebb** [comment]
Sentry fixed https://github.com/OpenDataServices/opendataservices-deploy/commit/b208a481dd0810402bb310d17316ab363ccb52b5

**Comment by Bjwebb** [comment]
Pull request merged and deployed https://github.com/OpenDataServices/org-ids/pull/101
