### ISSUE TITLE
Updates to GB-LAE

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/org-ids#105]
URL is wrong - http://local-authority-eng.alpha.openregister.org/records gives error.
Check/update to https://local-authority-eng.register.gov.uk/

Also issue with http://org-id.guide/list/GB-GOR.

**Comment by timgdavies** [comment]
Thanks @KDuerden - these are now fixed.

It appears when registers move from alpha to live, they move URLs without a redirect.

I'll look into whether there is a way we can watch better to find these updates in future.
