### ISSUE TITLE
Drop-down titles don't fit into allocated space

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#109]
The top drop-down is truncated in Chrome - Version 59.0.3071.115 (Official Build) (64-bit) / macOS 10.12.6

![screen shot 2017-07-31 at 12 25 39](https://user-images.githubusercontent.com/641009/28814136-57fe0e02-7694-11e7-885b-527bb26a61fe.png)

**Comment by robredpath** [comment]
Also: 

<img width="795" alt="screen shot 2017-08-01 at 08 43 44" src="https://user-images.githubusercontent.com/641009/28814452-8eaec0bc-7695-11e7-8965-9b0622fcc414.png">

**Comment by Bjwebb** [comment]
Dropdown has been replaced by a custom component on http://dev.org-id.guide/
