### ISSUE TITLE
Drop-downs are disproportionately large 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#110]
When I click on a drop-down to select something, they are very large. For long lists, eg the country list, this makes it harder to navigate. 

<img width="1005" alt="screen shot 2017-08-01 at 08 37 03" src="https://user-images.githubusercontent.com/641009/28814228-a679dfb6-7694-11e7-9200-1f6d6a84d53e.png">

**Comment by Bjwebb** [comment]
Dropdown has been replaced by a custom component on http://dev.org-id.guide/
