### ISSUE TITLE
Filtering UI is exposed even when it doesn't make sense

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#111]
For example, here I have no options to select but I'm given a drop-down anyway:

<img width="786" alt="screen shot 2017-08-01 at 08 39 10" src="https://user-images.githubusercontent.com/641009/28814330-06786464-7695-11e7-936c-efde356a7844.png">

**Comment by timgdavies** [comment]
I suggest we remove sub-category drop-downs from the front-page.

These should just be included in results pages to filter down the result set.

**Comment by Bjwebb** [comment]
This is now fixed on http://dev.org-id.guide
