### ISSUE TITLE
'countries' part of template is still rendered even when no country-specific registers are included in results

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#113]
A minor point, but it looks a bit odd to provide a box labelled 'Countries' when there aren't any, anywhere on the page. I'd prefer this to either be removed, or default to 'all countries', 'international' or some other suitable text to explain the geo scope of the register. 

<img width="1394" alt="screen shot 2017-08-01 at 08 49 01" src="https://user-images.githubusercontent.com/641009/28814994-b4d83014-7697-11e7-8ad8-180f5916158d.png">

**Comment by timgdavies** [comment]
Agreed. Where countries is blank, this box should not be displayed.

**Comment by Bjwebb** [comment]
Box is now hidden when there are no countries: http://dev.org-id.guide/results?structure=government_agency&substructure=&coverage=ZA&subnational=&sector=
