### ISSUE TITLE
'about' and download links look greyed out

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#114]
I had to click them to see if they worked or if they'd been disabled for some reason....

<img width="424" alt="screen shot 2017-08-01 at 09 05 05" src="https://user-images.githubusercontent.com/641009/28815593-ccfd1efa-7699-11e7-8507-57ae31cdb989.png">

**Comment by timgdavies** [comment]
Good point - suggest making this slightly heavier so that it is clear they are available as links.

**Comment by Bjwebb** [comment]
Boxes are now a slightly darker colour on http://dev.org-id.guide/results
