### ISSUE TITLE
Drop-downs on the 'about' page aren't populated

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#115]
<img width="582" alt="screen shot 2017-08-01 at 09 15 55" src="https://user-images.githubusercontent.com/641009/28815688-1686af1e-769a-11e7-867a-f44241dc30bc.png">

**Comment by timgdavies** [comment]
This is a bug that needs fixing.

**Comment by Bjwebb** [comment]
This has been fixed by removing the dropdowns http://dev.org-id.guide/about
