### ISSUE TITLE
Clicking the 'down arrow' on the home page doesn't open the drop-down

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#117]
You have to click the text instead...

![capture](https://user-images.githubusercontent.com/641009/28816220-f7a1039a-769b-11e7-8b5e-eff764b2ad50.PNG)

**Comment by timgdavies** [comment]
This is a bug and should be fixed.

**Comment by Bjwebb** [comment]
Fixed on http://dev.org-id.guide/
