### ISSUE TITLE
Text for 'suggested lists' and 'possible lists' is the same when matches are found

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#118]
Given that there is a difference between how the results should be interpreted by the user, perhaps these should be different?

**Comment by duncandewhurst** [comment]
The text is different on the [live version](http://org-id.guide/?structure=&coverage=NP&sector=) of the site:

>Suggested lists: We think one of the lists below will have a good chance of including the organisation(s) you are looking for... 

and

>Possible lists: It's possible you will find the organisation(s) you are looking for in one of the lists below...

**Comment by timgdavies** [comment]
This is a bug that needs to be fixed.

**Comment by Bjwebb** [comment]
Text now matches the live version of the site: http://dev.org-id.guide/results?structure=&coverage=NP&sector=
