### ISSUE TITLE
"back to results" doesn't function as expected

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/org-ids#119]
I noticed: after filtering (either homepage or lhs filters) I click on a record and then "back to results" link. However, I do not get the filtered list back at http://dev.org-id.guide/results

I'm imagining this might involve some code to do so - it's not a browser issue

**Comment by timgdavies** [comment]
This is a bug introduced by the new approach - so should be fixed.

**Comment by Bjwebb** [comment]
This should now work as expected on http://dev.org-id.guide

**Comment by stevieflow** [comment]
Have tested - agree.  Thanks
