### ISSUE TITLE
Autocomplete needs user to delete placeholder text before typing

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#138]
When I click the drop-down to a list, I can't just start typing to clear the placeholder. I have to first hit backspace, then start typing.

![image](https://user-images.githubusercontent.com/342624/28977889-c71b9a9e-793b-11e7-8479-e53da60389d8.png)

This isn't a very intuitive behaviour.

**Comment by andylolz** [comment]
This is particularly relevant for giant country list. I did not figure out the backspace trick, and found this infuriating.

**Comment by timgdavies** [comment]
Infuriation is not an experience we want. Ok - will investigate for fixes more urgently...

**Comment by andylolz** [comment]
> Infuriation is not an experience we want

Haha, ‘infuriating’ was a bad choice of words! I think I’m the same as Tom Steinberg on this: “Bad usability makes me grumpy and judgmental”! Apologies.

Looking at [the selectize.js site](http://selectize.github.io/selectize.js/), this looks like default behaviour. Appears to have been [reported here](https://github.com/selectize/selectize.js/issues/1302) (and I’d bet that’s a dupelicate.)

Anyway! I usually use [chosen](https://harvesthq.github.io/chosen/) for this sort of thing (mentioned on the selectize.js homepage.) Apparently this has “a few advantages” over chosen, but I’m not sure what they are. Would you consider switching?

Btw, here’s a super weird bug!
![wo3upbgwpe](https://user-images.githubusercontent.com/464193/29167059-db4894d4-7dc0-11e7-9cb2-76237dcb20f9.gif)

**Comment by timgdavies** [comment]
@andylolz Certainly would consider switching. @rbika might be able to highlight a particular reasons for the selectize choice. 

Flagging this also for @ccmdesign as a snagging issue.

**Comment by rbika** [comment]
Agree with you guys. I thought Selectize would be a good choice but. I wasn't aware of these problems. I'll give a look at Chosen. Does anyone have another suggestion?

**Comment by andylolz** [comment]
> Does anyone have another suggestion?

[select2](https://select2.github.io/) is the other popular choice. It’s possible it’s just down to which is simplest to re-skin (but I’m afraid I don’t know the answer to that.)

**Comment by Bjwebb** [comment]
Now using Chosen on http://org-id.guide/, which looks like it solves the problems.

**Comment by andylolz** [comment]
Really nice. Thanks!
