### ISSUE TITLE
ccmd-frontend branch does not disable selections returning no results  

### ISSUE THREAD

**Issue by edugomez** [OpenDataServices/org-ids#140]
[ccmd-frontend branch](https://github.com/OpenDataServices/org-ids/tree/ccmd-frontend/)

No results are returned http://dev.org-id.guide/results?structure=company&substructure=all&coverage=GB&subnational=GB-NIR&sector=all

The previous behaviour was disabling dropdown selections that wouldn't return any result.

**Comment by timgdavies** [comment]
@rbika Is there a straightforward fix for this?

**Comment by rbika** [comment]
@timgdavies I'm on it

**Comment by Bjwebb** [comment]
This is now fixed on http://dev.org-id.guide/results
