### ISSUE TITLE
position:fixed sidebar doesn’t fit on my little screen

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#150]
I have to zoom out to see the bottom of this sidebar:
![screen shot 2017-08-09 at 16 36 04](https://user-images.githubusercontent.com/464193/29130157-e8e65a40-7d20-11e7-9405-11eb3e65faaa.png)

**Comment by andylolz** [comment]
Refs #143.

**Comment by timgdavies** [comment]
Flagging to @ccmdesign as a snagging issue.

**Comment by Bjwebb** [comment]
Should now be fixed on http://org-id.guide/

**Comment by andylolz** [comment]
Looks good to me 👍
