### ISSUE TITLE
Long URLs / words flood out of cards on Chrome/OSX

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#151]
[E.g.](http://org-id.guide/results?structure=government_agency&substructure=all&coverage=AF&sector=humantiarian_relief)
![screen shot 2017-08-09 at 16 39 51](https://user-images.githubusercontent.com/464193/29130371-85632cae-7d21-11e7-86ed-103c484e4f42.png)

Looks fine on FF/OSX.

**Comment by timgdavies** [comment]
Flagging to @ccmdesign as a snagging issue

**Comment by Bjwebb** [comment]
Should now be fixed on http://org-id.guide/
