### ISSUE TITLE
Broken link (404) for US-EIN list

### ISSUE THREAD

**Issue by reidmporter** [OpenDataServices/org-ids#170]
Broken link from org-id.guide: https://www.irs.gov/businesses/small/article/0,,id=98350,00.html

**To search EINs of Exempt Orgs (nonprofits and charities, including: charitable organizations, churches and religions organizations, political organizations, private foundations, and more): https://apps.irs.gov/app/eos/**

**To search most public companies (those that are required to file forms with the US SEC): https://www.sec.gov/edgar.shtml*** 

*Maintained by Securities and Exchange Commission (SEC) of the US Government, not the Internal Revenue Service (IRS). Even though these filings usually provide EIN's issued by the IRS, I could see an argument being made for including US-SEC as a new list...?

For-profit companies EIN's are not a readily accessible from the IRS directly, but the article that describes EINs which I THINK is what the broken link used to refer to is: https://www.irs.gov/businesses/small-businesses-self-employed/employer-id-numbers-eins

**Comment by reidmporter** [comment]
Ahem, this is the broken link (below), the links in the full article are fine, though the links I gave above are probably more useful for MOST orgs than the Google/state-based search suggested by the Red Cross example.

![image](https://user-images.githubusercontent.com/15111135/30251690-0a1a1276-9633-11e7-8ff0-0f2a3562e59a.png)

**Comment by timgdavies** [comment]
Thanks for reporting this. I've staged updates over at https://github.com/org-id/register/pull/68 and those should get merged shortly.

**Comment by BobHarper1** [comment]
This can be closed thanks to org-id/register/pull/68
