### ISSUE TITLE
Move away from terminology of 'prefix'

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/org-ids#18]
At IODC someone suggested it could be more understandable to talk about finding the right registration body, rather than initially about "prefixes". (Although, "prefix" is probably still a useful term to use in the specifics of how identifiers get concatenated).

**Comment by timgdavies** [comment]
We're using the language of 'organisation identifier list' rather than prefix most of the time.

We need to review front-end and language on websites etc. but I think we have now moved away from too much talk of prefixes otherwise.

**Comment by edugomez** [comment]
@kindly I think the only references to _prefixes_ left are the ones in the _About_ page (which I think it's OK, but I have only skimmed through it) and in the `filter_and_score_results` function, where perhaps they should be replaced?

**Comment by timgdavies** [comment]
I'm fixing the about page and will push a branch with that fixed shortly.

**Comment by timgdavies** [comment]
Fixed in the about page on https://github.com/OpenDataServices/org-ids/tree/layout-edits
