### ISSUE TITLE
Using _preview_branch can lead to a KeyError for subnational lookup

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/org-ids#187]
I'm assuming this is because an older version of the data gets loaded, which leads to this problem https://github.com/OpenDataServices/org-ids/issues/186 (which is fixed in the latest data).

I've disabled _preview_branch on the live site for now http://org-id.guide/_preview_branch/example

**Comment by edugomez** [comment]
@Bjwebb I'm only able to reproduce the problem with this branch is the register https://github.com/org-id/register/tree/test-ae-dmcc. That branch started off from master and carries over the problem in #186. 

I've checked that 'owners' of branches in the register are not merging master often (mostly they are not merging master at all), so any bug picked from master at the time of branching off will stay in the branch despite any fixes in master. I think it would be good to remind everyone to merge from master often given that all branches in the register go 'live' automatically in the frontend application.

**Comment by edugomez** [comment]
Closing this issue as the problem goes beyond the bad data in subnational coverage. 

Opening #188 to investigate potential problems with data/schema caching.
