### ISSUE TITLE
Output the codelist (investigation)

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/org-ids#19]
Eventually, this list will replace: http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/

We should offer support for the formats and outputs that IATI currently provide - so providing the list accordingly will be a task

(however, there may be a number of related / pre tasks to this, but want to log this issue initially)

**Comment by stevieflow** [comment]
(assign to @Bjwebb for feedback)

**Comment by Bjwebb** [comment]
I think how we do this depends quite a bit on where the SSOT of the data is stored. Currently for our project this is airtable, but I'm not convinced that's going to be the correct choice going forward.

**Comment by Bjwebb** [comment]
This is being done in https://github.com/OpenDataServices/org-ids/issues/43
