### ISSUE TITLE
Text flooding in “How to use” sidebar

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#196]
E.g. here:
http://org-id.guide/list/BE-BCE_KBO

![screen shot 2018-02-19 at 14 29 38](https://user-images.githubusercontent.com/464193/36382594-7007c56a-1581-11e8-9bac-0d51a5a3d8e1.png)

**Comment by BobHarper1** [comment]
aye, we got #192 as well

**Comment by andylolz** [comment]
Good point – this is _pretty much_ the same issue, so closing.
