### ISSUE TITLE
List score circle (in the list details view) is huge on mobile

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#199]
Screenshot (from chrome devtools, for any small screen. But confirmed in situ on my galaxy S4 mini):
![screen shot 2018-02-21 at 11 01 52](https://user-images.githubusercontent.com/464193/36476801-d153b632-16f6-11e8-9bcf-425895441aaa.png)

**Comment by duncandewhurst** [comment]
I have the same issue in Firefox 59 on Ubuntu 16.04 when I snap the browser window to half the screen width:

![image](https://user-images.githubusercontent.com/19265814/40150652-f4c16a04-59ce-11e8-8790-5ab47d14b69a.png)
