### ISSUE TITLE
XML produced by org-id.guide appears to be invalid against IATI schema

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#204]
This XML:
http://org-id.guide/download.xml

…appears to be invalid against the IATI schema. Here’s a travis build where it fails to validate:
https://travis-ci.org/IATI/IATI-Codelists-NonEmbedded/builds/364483003

The issue appears to be instances where multiple comma-separated URLs are provided in the URL field. Like this one:
https://github.com/andylolz/IATI-Codelists-NonEmbedded/blob/915a02da95a876e6f852cb4ac5eb2321eb878f60/xml/OrganisationRegistrationAgency.xml#L2440

I suppose it would be preferable to pick a single URL, and perhaps add any other URLs to the description.

I ran into this problem whilst trying to update the relevant IATI codelist from org-id.guide (IATI/IATI-Codelists-NonEmbedded#247).

**Comment by Bjwebb** [comment]
Thanks for looking into this.

My question here is whether we should edit this in the data, e.g. https://github.com/org-id/register/blob/master/lists/pk/pk-vswa.json#L7 , or change our XML code to handle the data. I think changing the data is probably better, as commas in a url field seems like something that might trip other people up. @timgdavies What do you think?

**Comment by timgdavies** [comment]
Agreed that we should change the source. I'll look into this shortly and will revert.

**Comment by andylolz** [comment]
Great. Once this is sorted, I’ll update the PR to IATI.

**Comment by timgdavies** [comment]
I've updated org-id.guide sources so it should be possible to update the PR from the live source.

**Comment by andylolz** [comment]
Thanks @timgdavies - lgtm!
