### ISSUE TITLE
Surprising “Request research to identify an appropriate list” feature! What are the parameters?

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/org-ids#208]
The “request research” feature appears to have been added without fanfare (#136). Very cool! But I’m a bit concerned that it’s unclear what guarantees the results of this research come with.

By way of contrast, I notice the license of this repository includes [a disclaimer of warranty](https://github.com/OpenDataServices/org-ids/blob/7a8690d4/LICENSE#L591-L600) and declares [limitation of liability](https://github.com/OpenDataServices/org-ids/blob/7a8690d4/LICENSE#L602-L612). I wonder if it might help manage the expectations of those requesting research from an org-id researcher to include similar provisos.

**Comment by timgdavies** [comment]
Thanks @andylolz. 

Are there particular liability / warranty issues you are concerned about?

**Comment by andylolz** [comment]
Hi Tim!

> Are there particular liability / warranty issues you are concerned about?

I suppose warranties and liability declarations are mechanisms that help ensure everyone is on the same page. So I’m just talking about doing that, to ensure expectations are managed.

I arrived here from the following thread, which maybe helps clarify where I’m coming from:
https://discuss.iatistandard.org/t/approved-create-new-organisation-identifier-xi-iati-fiabel/1283/8

In the instance above, it seems a lot of trust is placed in the result. But in other instances, it’s not totally clear how that result was reached. Call me sceptical, but without a reproducible process and/or some sort of guarantee, I’m not sure how much faith I’d put in the result.

This might boil down to me not really understanding the relationship between org-id and IATI. I don’t know. With this on-demand research, I can see that a service is being offered, but there’s no public methodology; the guarantees are unstated… It _feels_ to me like something is missing here. But I don’t feel at all confident in that, so I’m happy to just flag it here and defer to your good judgement.

**Comment by andylolz** [comment]
The other bit of context here is: There’s a bunch of stuff on the XI-IATI list that really shouldn’t be there. But once an org is on there, there’s no going back.

Now, I assume that happened as a result of a lack of a robust process (predating org-id.guide, of course). So what I’m calling for here is a robust and moreover transparent process. But you don’t need to tell me that process – you need to tell the world! :) (via the org-id.guide website).

> But in other instances, it’s not totally clear how that result was reached

The example I had in mind here was not FIABEL, but this one: org-id/register#222 The working here is not provided, so it’s unclear what steps were taken to figure out the result. Maybe the process was robust here, but it’s not possible for me to verify that. So I immediately felt worried about the prospect of another entry into the XI-IATI list that maybe shouldn’t be there (in fact, the first thing I did was to check DAC channel codes). Note that I imagine this example is probably okay, and I’m a bit reluctant to talk about specifics.

> There is more information on the process at http://docs.org-id.guide/en/latest/contribute/

Thanks for pointing me to this! A bit unrelated, but: I’m not sure why requesting research (here entitled “requesting a new entry”) appears on the Contributing page. I’m struggling to understand a request as a contribution or a suggestion. It seems conceptually different from the other things on the page.

**Comment by timgdavies** [comment]
Thanks for the thoughtful engagement here: really useful to have eyes and reflections on this.

> The other bit of context here is: There’s a bunch of stuff on the XI-IATI list that probably shouldn’t be there (XI-IATI-IADB was an example highlighted to me recently). But once an org is on there, there’s no going back.

So - part of the idea of list scoring in org-id.guide is that it provides a possible method for 'going back' when something has ended up on a 'list of last resort' due to practical considerations. 

I.e. [XI-IATI](http://org-id.guide/list/XI-IATI) scores low because it is a third-party list - and if in future IADB is discovered on another, higher scoring, list then there would be at least a basis on which to suggest (a) publishers should use the higher scoring identifier; (b) data users should map where possible from the poorer quality, to the better quality identifier. 

But I'll not defend the particular decision making in any specific standards list of last resort. That said, there are lots of other institutional lists like XI-IATI that exist and are somewhat esoteric. E.g. the list of 'entities' on [XR-EUCB](http://org-id.guide/list/XR-EUCB) provides some interesting insights into those the EU have worked with.

> But you don’t need to tell me that process – you need to tell the world! :) (via the org-id.guide website).

Noted. Hoping to get opportunity to do some work on it before the summer is out. 

> Thanks for pointing me to this! A bit unrelated, but: I’m not sure why requesting research (here entitled “requesting a new entry”) appears on the Contributing page. 

Because not everyone can do the research themselves. But highlighting that something needs to be added is a valuable contribution in itself.

**Comment by andylolz** [comment]
Many thanks for this, Tim. All makes sense to me.

> But highlighting that something needs to be added is a valuable contribution in itself.

^^ Gotcha! Yes okay, I see what you mean.

**Comment by andylolz** [comment]
> > I’m not sure why requesting research (here entitled “requesting a new entry”) appears on the Contributing page.
> Because not everyone can do the research themselves. But highlighting that something needs to be added is a valuable contribution in itself.

Hang on… Highlighting that something needs to be added is covered in the “Proposing a new entry” section. I totally agree that that belongs on the contributing page – that’s not in question.

“Requesting a new entry” means something quite different – it’s about requesting research to find the most appropriate list and/or identifier for a given organisation, right?

I think the title “Requesting a new entry” is confusing, and I think including it on the “Contributing” page is also confusing. It sooooounds a bit like you muddled these two sections up in your answer. If that’s the case, that would seem to demonstrate my point that this is confusing.

**Comment by timgdavies** [comment]
I'm not sure I've muddled anything up here.

Requesting an entry is described as:

> When you have an organization or orgnanizations you want to provide an identifier for - but you can’t find any official identifier source, you can post a ‘REQUESTED’ issue.

This is assuming someone has tried to find the identifier themselves. Sometimes the reply will be to highlight that an existing identifier exists (that they have not managed to find), in other cases, this will spark investigation that leads to the proposal of a new list in org-id.guide. 

Proposing a new entry is described as:

> When you have identified a list that should be included in org-id.guide, you can post a ‘PROPOSAL’ issue, or submit a pull-request with a fully-researched list.


However - if there's another title that might address the confusion you find here - let me know and happy to see about updating the handbook.

**Comment by andylolz** [comment]
> I'm not sure I've muddled anything up here.

Okay – apologies! I wasn’t sure.

> > When you have an organization or orgnanizations

I’ve just sent [a PR to fix this typo](https://github.com/org-id/handbook/pull/8).

> > but you can’t find any official identifier source

“Official identifier source” == “list” == “entry”, right?

> Sometimes the reply will be to highlight that an existing identifier exists

With that in mind, I think “Request research to find an identifier” more clearly describes the task. The requested identifier might be on a new list, in which case it would trigger the proposal of a new “entry” or “list”. I.e. it would trigger the second task.
