### ISSUE TITLE
Decide on the SSOT for the list

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/org-ids#21]
as per #19 @Bjwebb says

> I think how we do this depends quite a bit on where the SSOT of the data is stored. Currently for our project this is airtable, but I'm not convinced that's going to be the correct choice going forward.

**Comment by Bjwebb** [comment]
Things to consider:
* How do we inspect the history of the list (version control)
* How do we ensure the list if accissble, bath to people and machine users
* How do we suggest changes to the list, without directly changing it?

**Comment by stevieflow** [comment]
This might be useful / relevant: https://github.com/OpenAgFunding/development/issues/16

**Comment by timgdavies** [comment]
We now have the codes folder here https://github.com/OpenDataServices/org-ids/tree/master/codes which is our SSOT.
