### ISSUE TITLE
List for Economic and Social Fund for Development, Lebanon

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [OpenDataServices/org-ids#219]
Hi team,

The Economic Social Fund for Development (ESFD) in Lebanon have expressed an interest in becoming an IATI publisher.

Website: http://www.esfd.cdr.gov.lb/

A Government body, they have advised that they are not registered with any existing Lebanese or international identifiers, and are not provided with a code from the Government.

My feeling is that we will have to use XI-IATI but I wanted to run it past you guys first in case you could uncover any alternatives!

Thanks,
Josh

**Comment by JoshStanleyDevInit** [comment]
Hi team,

Just checking in on this one - can you advise if and when this issue might be reviewed?

Thanks!
Josh

**Comment by siwhitehouse** [comment]
@JoshStanleyDevInit I've just seen this. Unfortunately it was raised in the wrong repo. I see that you have raised this on the [IATI discuss list](https://discuss.iatistandard.org/t/approved-new-organisation-identifier-xi-iati-esfd/1898) and so I'll close this issue
