### ISSUE TITLE
Kenya duplicate

### ISSUE THREAD

**Issue by benparkergit** [OpenDataServices/org-ids#24]
ke-cr.json 
ke-rco.json 

These appear to be duplicates, both referring to the Register of Companies.

**Comment by timgdavies** [comment]
Thanks Ben: yes - we're aware of some of these duplicates right now whilst we are cleaning up and merging a list imported from Open Corporates and IATI.

We have a 'confirmed' flag in the individual organisation list json to indicate when that review is complete, but perhaps we should have something more explicit to separate the proposed and confirmed entries during this first phase of getting the list set-up.

**Comment by timgdavies** [comment]
I've just removed ke-cr.json from the master branch and the AirTable.
