### ISSUE TITLE
Malasyian Identifier Sources

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#26]
From Swee Meng on Sinar Project.

* Company Commission Number 
* Construction Industry Development Board - own company register and identifiers  (secondary)
* Government Contracts Vendor ID (found on some procurement lists)

Non-profits:

* Registrar of Society (but not many registered...)

Government Agency 

* Check with Sinar about source of documents. Sinar open spending has a source.

**Comment by sweemeng** [comment]
I suggest to look at the dataset at http://sinarproject.org/en/projects/scrapers-1/construction-industry-development-board-cidb-database to test. Hope it is useful

**Comment by timgdavies** [comment]
Continued in https://github.com/org-id/register/issues/33
