### ISSUE TITLE
Netherlands Overheid.nl Web Metadata Standard

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#30]
Based on conversations with @rolfkleef at OGP I've added:

[NL-OWMS](https://github.com/OpenDataServices/org-ids/blob/master/codes/nl/nl-owms.json) to the codelist (visible [more easily in AirTable here](https://airtable.com/shrsA8pTLjBiR6SVs/tblAPFyWmOBCJeiCU/viwRSCUQUTCEVFwC9/rec7ohtKutxN4rqCU))

@rolfkleef Would you be able to check that I've described the service there right.

This has also raised two interesting issues around:

* Legal characters for identifiers (e.g. ```'s-Graveland``` as an identifier where it looks like the ' breaks even overheid.nl's [own RDF and N3 downloads versions!](http://standaarden.overheid.nl/owms/terms/'s-Graveland_(gemeente).html))
* The guidance we should give when URIs are available.

I'll open separate issues for these.

**Comment by rolfkleef** [comment]
Looks good to me!

You might also want to check work by Open State Foundation on organisations keeping lists of (Dutch) gov and semi-gov id's: https://github.com/openstate/datasets/tree/master/osn

Lex Slaghuis mentioned mapping id's between lists by various authorities, as part of the Accountability Hack in September, https://github.com/openstate/datasets/blob/master/osn/master-view.csv

I've reported that URI problem to their contact address, let's see what can be done about that!

-----

Re: URIs

I'd be in favour of pushing towards a URI-compatible naming scheme... in IATI, there are various other codelists as well that contain a vocabulary identifier with a code within that vocabulary.

An "org id vocabulary"-ontology, where information about a particular registrar could be made available as properties in e.g. the joinedupdata.org store, seems useful.

**Comment by rolfkleef** [comment]
Just had a response about the URIs: known issue. They were inspired by DBPedia to use special characters, but this results in various problems, so they're working on a new URI system without special characters.

**Comment by timgdavies** [comment]
A codelist has been added https://github.com/OpenDataServices/org-ids/blob/master/codes/nl/nl-owms.json

I'll open a separate issue re: URL-compatible naming scheme
