### ISSUE TITLE
Regional Jurisdiction Codes

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#33]
At the moment we allow national jurisdictions only (e.g. each list must either be specific to one or more **countries**, or have jurisdiction left blank). 

However, PublicBodies.org has a list of European Union bodies (http://publicbodies.org/eu)

Should we have jurisdiction codes for regional blocks? Or some sort of multilateral code?

**Comment by timgdavies** [comment]
E.g. a jursidiction code for 'EU'

**Comment by benparkergit** [comment]
Here's the UN list: http://www.un.org/en/sections/about-un/funds-programmes-specialized-agencies-and-others/index.html
