### ISSUE TITLE
Updated search and results interface

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#38]
Because the algorithm defined in #37 needs to be able to be shared with people independently of this implementation, consideration of how we present the UI for org-id.WHATEVER is being considered separately

**Comment by edugomez** [comment]
![org_ids_38](https://cloud.githubusercontent.com/assets/5618508/23122595/be2503aa-f75c-11e6-81f5-f28d1f42df2c.png)

**Comment by edugomez** [comment]
![org_ids_38_co](https://cloud.githubusercontent.com/assets/5618508/23122602/c83f6768-f75c-11e6-8902-856ddd0a30a8.png)

**Comment by timgdavies** [comment]
I've just been testing this interface - and it works nicely.

**Comment by robredpath** [comment]
Done, but need to check with @Bjwebb that the lack of copy doesn't interfere with his demo-ing at TAG
