### ISSUE TITLE
Filtering for sub-categories (e.g. sub-jurisdictions or sub-structures)

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/org-ids#39]
This is a new dimension to the algorithm (impacting #37) and UI (impacting #38)

**Comment by edugomez** [comment]
Couple of questions to be addressed regarding structure ('type of organisation'):

- Do all substructure (e.g. `company/listed`) need to include by default the parent structure (e.g. `company`) in the array of structures? Or can we have a structure array with only a substructure (e.g. `company/listed` but not `company`)  

- Probably the problem boils down to what just `company` means in structure . Does it mean that it covers all type of companies or just _some_ types of companies? If it is the latter, then it makes sense that `company` is always included with any substructure (this would be very similar to country/subnational coverage case). If, on the contrary, `company` means all kind companies (in the sense of unspecified) then probably it doesn't make sense to have e.g. `company` and `company/listed` in the same array, unless `company/listed` is indicating that listed companies have a special weight in a list that also cover other type of companies

**Comment by timgdavies** [comment]
I think the other way of thinking about this is:

> What does a user expect when they select 'company'

I think of this as the case where the user may not really know what kind of company they are looking for. 

A list which is tagged as **only** 'company' is a list which is more appropriate for this case. 

A list which is tagged as **company/listed** is likely to be narrower than they were looking for, unless they then choose to narrow their search to only listed companies. 

When they do narrow their search to **company/listed** then only things with **company/listed** or * for type would be relevant.
