### ISSUE TITLE
Consolidated list in XML, JSON and CSV formats

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#43]
It should be possible for users to download copies of all confirmed codes (including deprecated codes, suitably marked) in:

* IATI XML Codelist format
* CSV
* JSON

Containing at least:

* Title
* Description
* Code
* URL

And if appropriate for file-size etc. also:

* Finding the identifiers
* Example Identifiers
* Data access details (e.g. CSV, JSON etc.)
* Data license
* Data features (shareholders, address etc.)

**Comment by timgdavies** [comment]
IATI XML Codelist form https://github.com/OpenDataServices/org-ids/blob/scripts/tools/codes-to-iati.py

**Comment by timgdavies** [comment]
We explored how this could be:

* Generated by Travis and pushed;
* Generated server side;

Updating the server on each update to master is desirable anyway - so that might fit?

**Comment by timgdavies** [comment]
Good to see the CSV and JSON outputs. If we can get the XML output, and document that in the about page by the end of this sprint, that will be very valuable for the IATI tag.

**Comment by Bjwebb** [comment]
Here's the current IATI XML list for comparison https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/master/xml/OrganisationRegistrationAgency.xml

**Comment by robredpath** [comment]
Instead of buttons, we'll have a Download page where the URLs for the various downloads live
