### ISSUE TITLE
Consider using language of 'Non-profit' rather than 'Charity' 

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#56]
For international work, many organisations we are currently structuring as 'charity' might be better represented as 'NGOs'.

A language of 'Non-profit' at the top level, with Charity and NGO as categories under this, might help.

**Comment by benparkergit** [comment]
The terminology of the original jurisdiction should be used, surely? Plenty of UK NGOs don't like the term charity, but that's the law they operate under.

**Comment by timgdavies** [comment]
The difficulty is that we want to have a fairly clear taxonomy for searching for identifiers - that can be applied globally. 

The descriptions of lists would still use domestic terminology - but the classification scheme needs to be globally applicable.

**Comment by benparkergit** [comment]
OK, but the classification of non-profit types is not just a technical exercise. What counts as a "local" NGO is right now bogged in politics in the context of the calls for "localization" in the humanitarian sector.

**Comment by timgdavies** [comment]
Picked up in https://github.com/org-id/register/issues/29
