### ISSUE TITLE
UK Alpha Registers: Local Authorities (England), Government Organisations

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/org-ids#67]
**1** The version controlled registers (including identifiers) are in alpha. Propose we review and decide when they are mature enough to use across:

1. [360Giving](http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier)
2. [OCDS](http://standard.open-contracting.org/latest/en/)
3. [IATI](http://iatistandard.org/) (for raising with the secretariat?)

**2** Currently, the 360Giving validator relies on the [IATI agency list](http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/). Are changes needed?

More info:

- [The register of government organisations is now in alpha (blog)](https://data.blog.gov.uk/2017/03/27/the-register-of-government-organisations-is-now-in-alpha/) | [register](http://government-organisation.alpha.openregister.org/)
- [Local authority England alpha register (blog)](https://data.blog.gov.uk/2016/09/07/local-authority-england-alpha-register/) | [register](http://local-authority-eng.alpha.openregister.org/records)

**Comment by Bjwebb** [comment]
2) Yes, but I'm not sure when. This page of the docs will also need changing appropriately http://www.threesixtygiving.org/standard/identifiers/. The IATI list should also be [pulled directly from org-id](https://docs.google.com/document/d/1JTw_OMEZpiKrgBfCPVeLYPNmkt7cZ_Qf0s8aN4_QfxM/edit#heading=h.cbznjcta6a8r) at some point, but 360Giving doesn't necessarily need to wait for that.

**Comment by ekoner** [comment]
Paul Downey has confirmed register should be stable: https://twitter.com/psd/status/846417891759181824

> if nothing else the URL will change when it goes to beta, but in this case the data comes from GOV.UK and has been stable for some time.

**Comment by timgdavies** [comment]
In #74 I've got suggested updates for the Gov Organisations Register and Local Authority register.
