### ISSUE TITLE
ISAAR/EAC CPF standard

### ISSUE THREAD

**Issue by rolfkleef** [OpenDataServices/org-ids#90]
New to me, perhaps relevant to org-ids? The Dutch national archive now has an ["actor register"](https://actorenregister.nationaalarchief.nl/) about government bodies since around 1975 (local and provincial bodies are still being added), with a data format based on the [International Standard Archival Authority Record For Corporate Bodies, Persons and Families (ISAAR CPF)](https://en.wikipedia.org/wiki/International_Standard_Archival_Authority_Record) and accessible as [EAC-CPF XML](https://en.wikipedia.org/wiki/Encoded_Archival_Context).

It seems to have an (optional, 0..n) id like `<entityId localType="HANDLE">10648/5e15ff63-0d72-46ab-9b04-13da850ce31d</entityId>` and a URI like http://hdl.handle.net/10648/5e15ff63-0d72-46ab-9b04-13da850ce31d

**Comment by timgdavies** [comment]
Taken forward in https://github.com/org-id/register/issues/31
