### ISSUE TITLE
Separate out codes directory and rename

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#91]
I've started looking at separating out the register and exploration application.

The goal here is to have the application pick-up codes from their own repository at https://github.com/org-id/register so that issues and pull requests against the codes are distinguished more clearly from issues / requests about the preview application.

**Comment by Bjwebb** [comment]
Could be useful to preserve some of the history for the codes schema folders in that repo? Here's a quick attempt at what that could look like - https://github.com/Bjwebb/org-ids-registry (doesn't include any commits for the web app).

**Comment by timgdavies** [comment]
That's great! Thanks. If you PR that to register will that give us the history? Or would we need to take another approach to get this history into place.

**Comment by Bjwebb** [comment]
Someone would need to force push to the "register" repository. I can do that if I have permission.

**Comment by timgdavies** [comment]
Consider yourself invited and with privileges granted.

**Comment by Bjwebb** [comment]
Done. Leaving this issue open because issues still want moving/

**Comment by timgdavies** [comment]
Moving the issues now.
