### ISSUE TITLE
New registers from the registers.gov.uk team

### ISSUE THREAD

**Issue by Jamie-Atkinson** [OpenDataServices/org-ids#92]
Hi all

I work as a data analyst for the government digital service (GDS). Edafe Onerhime replied to my tweet promoting the principal-local-authority register we just moved into alpha for feedback and introduced me to your tool

Really glad to see some of our registers already feature on your tool (government-organisation and local-authority-eng).

I just wanted to point out that we also have the following registers ready to use and we would love to see them feature on your service:

country register: https://country.register.gov.uk/

territory register: https://territory.register.gov.uk/

government service: https://government-service.register.gov.uk/

internal-drainage-boards: https://internal-drainage-board.register.gov.uk/

local-authority-sct: https://local-authority-sct.register.gov.uk/

prison-estate: https://prison-estate.register.gov.uk/

registration-district: https://registration-district.register.gov.uk/

we are working on many other registers, full details of the registers pipeline can be found here:

https://registers.cloudapps.digital/registers

my direct email is jamie.atkinson@digital.cabinet-office.gov.uk and I would love to hear from you about our registers and anyway you think we could improve.

more information about registers:
https://www.gov.uk/government/publications/registers/registers
https://gds.blog.gov.uk/2015/10/13/the-characteristics-of-a-register/

all the best

Jamie

**Comment by timgdavies** [comment]
Thanks for pointing to these. From the list, I understand that:

* Internal drainage boards
* Prison Estate
* Local Authorities in Scotland

might all qualify as organisation lists. 

I've got a pull request for the Scottish LA list, and will look at research into the others shortly.

**Comment by timgdavies** [comment]
I've opened requests for [Drainage Boards](https://github.com/org-id/register/issues/28) and [Prison Estate](https://github.com/org-id/register/issues/28) in our updated register repo.
