### ISSUE TITLE
government-organisation and local-authority-eng register incorrect links

### ISSUE THREAD

**Issue by Jamie-Atkinson** [OpenDataServices/org-ids#93]
Hi all

you are currently linking to 
https://government-organisation.alpha.openregister.org/
and
https://local-authority-eng.alpha.openregister.org
for these registers.

they have now moved out of alpha and onto the gov.uk domain, could these links be updated to:

https://government-organisation.register.gov.uk/
and
https://local-authority-eng.register.gov.uk/

respectively please

all the best

Jamie

**Comment by timgdavies** [comment]
Thanks for the pointer on these. The links have been updated.
